### ISSUE TITLE
Program Errors Out

### ISSUE THREAD

**Issue by szereka** [TwitchRecover/TwitchRecover#84]
Hello Here is a Copy Paste from PC .

Link used https://www.twitch.tv/videos/953959175 Works  Streamed 2021-03-18 CET
Link used https://www.twitch.tv/videos/955176941 Errors Out Streamed 2021-03-19 CET

C:\Twitch>Twitch.Recover.exe

DISCLAIMER:
This is only the alpha version of this program.
This should not be treated as a complete and final program.
There may be bugs and issues, which if you do experience please report on the Github project page - https://github.com/twitchrecover/twitchrecover
Thank you for your understanding.

Welcome to Twitch Recover!
The number one Twitch recovery tool created by Daylam Tayari (https://github.com/daylamtayari)
If you like this tool please help support me: https://paypal.me/daylamtayari https://cash.app/$daylamtayari BTC: 15KcKrsqW6DQdyZPrgRXXmsKkyyZzHAQVX

Menu:
Streams:
1. Get a live stream link (get the M3U8 stream link of a live stream).
2. Download a stream live. (Currently unavailable, coming in the beta)

VODs:
3. Get the link to a VOD (including sub-only).
4. Download a VOD (including sub-only).
5. Recover a VOD - 60 days maximum (can be less in rare cases).

Highlights:
6. Retrieve the link to a highlight.
7. Download a highlight.
8. Recover a highlight.

Videos:
9. Check if a VOD/highlight has muted segments.
10. 'Unmute' a VOD/highlight (be able to view the muted segments of the M3U8).
11. Download an M3U8 file.
12. Convert a TS file to MP4.

Clips:
13. Retrieve permanent link of a clip - never deleted.
14. Download a clip.
15. Recover ALL clips from a stream - NO time limit.

Mass options: (Currently unavailable, coming in the beta)
16. Mass recover options. (Currently unavailable, coming in the beta)
17. Mass download options. (Currently unavailable, coming in the beta)
Please enter the number of the option you want to select (number between 1-17 inclusive): 4

VOD downloading:
Please enter the link of the VOD to download: https://www.twitch.tv/videos/955176941
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:97)
        at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:152)
        at TwitchRecover.CLI.Handlers.VODHandler.download(VODHandler.java:71)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:41)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)

C:\Twitch>

**Comment by daylamtayari** [comment]
Could you please verify that your install is not corrupted or even just redownload the program because I just tried this on my end and it worked totally fine without any issues.

**Comment by szereka** [comment]
2 diffrent PCs 1 Win 10 and second PC is a Win7

**Comment by daylamtayari** [comment]
You downloaded the exe file and ran it directly right?

**Comment by daylamtayari** [comment]
Pardon me, Ive being able to replicate the bug. 
Let me look into this.

**Comment by szereka** [comment]
=)

**Comment by daylamtayari** [comment]
Found the issue, so it is because that VOD is on a new Twitch VOD server I was not previously aware of.
This server in particular: `https://dgeft87wbj63p.cloudfront.net/`.
So the M3U8 playlist for this VOD is: https://dgeft87wbj63p.cloudfront.net/a659851a83428681f9a3_orbitalpotato_41474534044_1616169889/chunked/index-dvr.m3u8

**Comment by daylamtayari** [comment]
I have added the domain to the domain tracking files which the program pulls every time it launches so this should now work fine on anyone's end.
Going to be closing this issue since it has been resolved and thank you very much for making this since this allowed me to detect a new VOD server I was not aware of.

**Comment by minerva1993** [comment]
@daylamtayari Seems that some of servers are still missing, such as d1m7jfoe9zdc1j.cloudfront.net

Noticed from 
https://d1m7jfoe9zdc1j.cloudfront.net/aacbe9ddc9b18c02b403_ok_ja_41091972429_1616252437/chunked/526.ts
which corresponding to the sub only vod https://www.twitch.tv/videos/956473664

**Comment by daylamtayari** [comment]
@minerva1993 Thank you, I still need to automate the domain collection so as of right now Im adding the domains manually.
I just added that domain.
